export type MiniEpisodeSeed = {
  id: string;
  episode: string;
  year: number;
  autor: string;
  coverImage: string;
};

export const miniEpisodeSeeds: MiniEpisodeSeed[] = [
  {
    id: 'K01',
    episode: 'und die Geisterlampe',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K02',
    episode: 'Dunkle Vergangenheit',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K03',
    episode: 'Entführt',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K04',
    episode: 'Verschwörung auf der Eagle Ranch',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K05',
    episode: 'SOS',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K06',
    episode: 'Der graue Dämon',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K07',
    episode: 'Das Lehrstück',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K08',
    episode: 'Das Rätsel der schwarzen Nadel',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K09',
    episode: 'Der verschwundene Superstar',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K10',
    episode: 'Manches verlernt man nie',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K37',
    episode: 'Psychomoon',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K38',
    episode: 'Jagd auf den Weihnachtsmann',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.webp',
  },
  {
    id: 'K11',
    episode: 'Der siebte Gast',
    year: 2014,
    autor: 'André Minninger',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K12',
    episode: 'Bis um sieben zurück',
    year: 2014,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K13',
    episode: 'Bobs schwerste Stunde',
    year: 2014,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K14',
    episode: 'Die rote Sieben',
    year: 2014,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K15',
    episode: 'Schutzgeld',
    year: 2014,
    autor: 'Ben Nevis',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K16',
    episode: 'Die siebte Frau des Leuchters',
    year: 2014,
    autor: 'Christoph Dittert',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K17',
    episode: 'Die verschwundene Torte',
    year: 2014,
    autor: 'André Marx',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.webp',
  },
  {
    id: 'K21',
    episode: 'Immer und immer wieder',
    year: 2016,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-zeitgeist.webp',
  },
  {
    id: 'K22',
    episode: 'Der Raub der Zehntausend',
    year: 2016,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-zeitgeist.webp',
  },
  {
    id: 'K23',
    episode: 'Der verschwundene Zeitgeist',
    year: 2016,
    autor: 'André Minninger',
    coverImage: 'covers/kurzgeschichten-zeitgeist.webp',
  },
  {
    id: 'K24',
    episode: 'Leaving Nineteen Sixty-four',
    year: 2016,
    autor: 'Ben Nevis',
    coverImage: 'covers/kurzgeschichten-zeitgeist.webp',
  },
  {
    id: 'K25',
    episode: 'Rückwärtsgang',
    year: 2016,
    autor: 'André Marx',
    coverImage: 'covers/kurzgeschichten-zeitgeist.webp',
  },
  {
    id: 'K26',
    episode: 'Zeit der Opfer, Zeit der Wunder',
    year: 2016,
    autor: 'Christoph Dittert, Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-zeitgeist.webp',
  },
  {
    id: 'K31',
    episode: 'Das schwarze Verlies',
    year: 2018,
    autor: 'Ben Nevis',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.webp',
  },
  {
    id: 'K32',
    episode: 'Schwarze Seelen',
    year: 2018,
    autor: 'André Minninger',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.webp',
  },
  {
    id: 'K33',
    episode: 'Ein schwarzer Tag für Mr. Kingstone',
    year: 2018,
    autor: 'Christoph Dittert',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.webp',
  },
  {
    id: 'K34',
    episode: 'Wer hat Angst vorm Schwarzen Mann',
    year: 2018,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.webp',
  },
  {
    id: 'K35',
    episode: 'Die schwarze PhantOma',
    year: 2018,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.webp',
  },
  {
    id: 'K36',
    episode: 'Das schwarze Nest',
    year: 2018,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.webp',
  },
];

