export type MiniEpisodeSeed = {
  id: string;
  episode: string;
  year: number;
  autor: string;
  coverImage: string;
};

export const miniEpisodeSeeds: MiniEpisodeSeed[] = [
  {
    id: 'K01',
    episode: 'K01: und die Geisterlampe',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K02',
    episode: 'K02: Dunkle Vergangenheit',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K03',
    episode: 'K03: Entführt',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K04',
    episode: 'K04: Verschwörung auf der Eagle Ranch',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K05',
    episode: 'K05: SOS',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K06',
    episode: 'K06: Der graue Dämon',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K07',
    episode: 'K07: Das Lehrstück',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K08',
    episode: 'K08: Das Rätsel der schwarzen Nadel',
    year: 2011,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K09',
    episode: 'K09: Der verschwundene Superstar',
    year: 2011,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K10',
    episode: 'K10: Manches verlernt man nie',
    year: 2011,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-geisterlampe.png',
  },
  {
    id: 'K11',
    episode: 'K11: Der siebte Gast',
    year: 2014,
    autor: 'André Minninger',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K12',
    episode: 'K12: Bis um sieben zurück',
    year: 2014,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K13',
    episode: 'K13: Bobs schwerste Stunde',
    year: 2014,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K14',
    episode: 'K14: Die rote Sieben',
    year: 2014,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K15',
    episode: 'K15: Schutzgeld',
    year: 2014,
    autor: 'Ben Nevis',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K16',
    episode: 'K16: Die siebte Frau des Leuchters',
    year: 2014,
    autor: 'Christoph Dittert',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K17',
    episode: 'K17: Die verschwundene Torte',
    year: 2014,
    autor: 'André Marx',
    coverImage: 'covers/kurzgeschichten-raetsel-der-sieben.png',
  },
  {
    id: 'K21',
    episode: 'K21: Immer und immer wieder',
    year: 2016,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-zeitgeist.png',
  },
  {
    id: 'K22',
    episode: 'K22: Der Raub der Zehntausend',
    year: 2016,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-zeitgeist.png',
  },
  {
    id: 'K23',
    episode: 'K23: Der verschwundene Zeitgeist',
    year: 2016,
    autor: 'André Minninger',
    coverImage: 'covers/kurzgeschichten-zeitgeist.png',
  },
  {
    id: 'K24',
    episode: 'K24: Leaving Nineteen Sixty-four',
    year: 2016,
    autor: 'Ben Nevis',
    coverImage: 'covers/kurzgeschichten-zeitgeist.png',
  },
  {
    id: 'K25',
    episode: 'K25: Rückwärtsgang',
    year: 2016,
    autor: 'André Marx',
    coverImage: 'covers/kurzgeschichten-zeitgeist.png',
  },
  {
    id: 'K26',
    episode: 'K26: Zeit der Opfer, Zeit der Wunder',
    year: 2016,
    autor: 'Christoph Dittert, Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-zeitgeist.png',
  },
  {
    id: 'K31',
    episode: 'K31: Das schwarze Verlies',
    year: 2018,
    autor: 'Ben Nevis',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.png',
  },
  {
    id: 'K32',
    episode: 'K32: Schwarze Seelen',
    year: 2018,
    autor: 'André Minninger',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.png',
  },
  {
    id: 'K33',
    episode: 'K33: Ein schwarzer Tag für Mr. Kingstone',
    year: 2018,
    autor: 'Christoph Dittert',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.png',
  },
  {
    id: 'K34',
    episode: 'K34: Wer hat Angst vorm Schwarzen Mann',
    year: 2018,
    autor: 'Marco Sonnleitner',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.png',
  },
  {
    id: 'K35',
    episode: 'K35: Die schwarze PhantOma',
    year: 2018,
    autor: 'Kari Erlhoff',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.png',
  },
  {
    id: 'K36',
    episode: 'K36: Das schwarze Nest',
    year: 2018,
    autor: 'Hendrik Buchna',
    coverImage: 'covers/kurzgeschichten-schwarze-tag.png',
  },
];
